class AgriLanguage {
  static const Map<String, Map<String, String>> values = {
    'en': {
      'title': 'AgriSense',
      'language': 'English',
      'switchLanguage': 'हिंदी (Indic)',
      'urgentAlert': 'Urgent Alert',
      'urgentAlertDesc': 'Irrigation needed for North Field. Soil moisture below 15%.',
      'weatherToday': 'Weather Today',
      'pune': 'Pune, Maharashtra',
      'rainfallChance': 'Rainfall Chance',
      'probability': '20% probability',
      'partlyCloudy': 'Partly Cloudy',
      'soilHealth': 'Soil Health',
      'optimal': 'Optimal',
      'nitrogen': 'Nitrogen',
      'high': 'High',
      'phLevel': 'pH Level',
      'viewDetailedReport': 'View Detailed Report',
      'marketPrice': 'MARKET PRICE',
      'quintal': 'Quintal',
      'fromLastWeek': 'from last week',
      'logHarvest': 'Log Harvest',
      'needExpertAdvice': 'Need expert advice?',
      'helperMic': 'Tap the mic and say "Check my tomato leaf health"',
      'quickInsights': 'Quick Insights',
      'cropGrowthPhase': 'Crop Growth Phase',
      'soybeansStage': 'Soybeans: Vegetative Stage (V3)',
      'satelliteView': 'Field Satellite View',
      'updatedHoursAgo': 'Updated 2 hours ago',
      'home': 'Home',
      'advice': 'Advice',
      'weather': 'Weather',
      'crops': 'Crops',
      'expert': 'Expert',
      
      // Advice Tab
      'cropRecommendations': 'Crop Recommendations',
      'aiDrivenPlanting': 'AI-driven planting strategies based on your current field data.',
      'soilType': 'SOIL TYPE',
      'redSoil': 'Red Soil',
      'richInIron': 'Rich in Iron Oxide',
      'waterLevel': 'WATER LEVEL',
      'marketDemand': 'MARKET DEMAND',
      'highDemand': 'High Demand',
      'pulseCropsTrend': 'Pulse crops trending +14% locally',
      'groundnut': 'Groundnut',
      'match': 'Match',
      'potentialYield': 'POTENTIAL YIELD',
      'tonsHectare': 'Tons/Hectare',
      'waterReq': 'Water Req.',
      'duration': 'Duration',
      'days': 'Days',
      'startPlanting': 'Start Planting Plan',
      'pigeonPea': 'Pigeon Pea',
      'sorghum': 'Sorghum',
      'viewDetails': 'View Details',
      'soilNutrientBalance': 'Soil Nutrient Balance',
      'nutrientTip': 'Tip: Adding organic mulch will help retain moisture in Red Soil during the next growth cycle.',
      
      // Weather Tab
      'weatherAdvisory': 'Weather & Advisory',
      'weatherSub': 'Real-time agricultural insights for your farm.',
      'drySpellAlert': 'Dry Spell Alert',
      'drySpellDesc': 'Low precipitation forecast for next 10 days. Moisture levels dropping in Sector B-4.',
      'delaySowing': 'Delay sowing',
      'increaseWater': 'Increase water',
      'viewDetailedPlan': 'View Detailed Plan',
      'currently': 'CURRENTLY',
      'humidity': 'Humidity',
      'nextIrrigation': 'Next Irrigation Window',
      'recommendedAmt': 'Recommended: 12L per m²',
      'outlook': '7-Day Farming Outlook',
      'mon': 'MON',
      'tue': 'TUE',
      'wed': 'WED',
      'sprayingOk': 'Spraying OK',
      'fertilize': 'Fertilize',
      'fertilizerWindow': 'Fertilizer Window',
      'optimalTime': 'Optimal Time',
      '48hours': 'In 48 Hours',
      'soilCondOpt': 'Soil conditions will be optimal for nitrogen absorption following Wednesday\'s light rain.',
      'recommended': 'RECOMMENDED',
      'ureaApp': 'Urea Application (Sector A)',
      'ureaAmount': 'Apply 50kg/hectare',
      'sensorNetwork': 'Soil Moisture Sensor Network',
      'sensorDesc': 'Real-time data from 24 IoT ground sensors.',
      'fullscreenMap': 'Fullscreen Map',
      'thermalView': 'Switch to Thermal View',
      'normalView': 'Switch to Normal View',

      // Crops Tab
      'myCrops': 'My Crops',
      'plantedOn': 'Planted on',
      'daysRemaining': 'days to harvest',
      'activeFields': 'Active Fields',
      'addNewCrop': 'Add Crop',
      'logNewHarvest': 'Log Harvest Record',

      // Expert Tab
      'newDiagnosis': 'New Diagnosis',
      'diagnosisDesc': 'Upload a photo or describe the issue via voice to get instant AI-driven health analysis.',
      'takePhoto': 'Take Photo',
      'processed': 'PROCESSED',
      'ongoingDiagnosis': 'Ongoing Diagnosis',
      'analyzingRice': 'ANALYZING RICE BLAST SYMPTOMS',
      'crossReference': 'Cross-referencing symptoms with localized weather data and soil nitrogen levels...',
      'cancel': 'Cancel',
      'rythuExpert': 'Rythu Seva Kendra Expert',
      'specialistAvail': 'Our local specialists are available for a video call or field visit today.',
      'callNow': 'Call Now',
      'bookVisit': 'Book Visit',
      'historicalLogs': 'Historical Logs',
      'viewAll': 'View All',
      'resolved': 'Resolved',
      'inReview': 'In Review',
      'tomatoWilt': 'Tomato Wilt',
      'tomatoWiltDesc': 'Success: Copper fungicide applied. Growth recovered by 15%.',
      'maizeChlorosis': 'Maize Chlorosis',
      'maizeChlorosisDesc': 'Expert assigned. Waiting for soil moisture analysis.',
      'cottonAphids': 'Cotton Aphids',
      'cottonAphidsDesc': 'Bio-pesticide treatment completed. Field cleared.',
    },
    'hi': {
      'title': 'कृषि-सेंस',
      'language': 'हिंदी',
      'switchLanguage': 'English',
      'urgentAlert': 'तत्काल सूचना',
      'urgentAlertDesc': 'उत्तरी क्षेत्र के लिए सिंचाई आवश्यक है। मिट्टी की नमी 15% से कम है।',
      'weatherToday': 'आज का मौसम',
      'pune': 'पुणे, महाराष्ट्र',
      'rainfallChance': 'बारिश की संभावना',
      'probability': '20% संभावना',
      'partlyCloudy': 'आंशिक रूप से बादल',
      'soilHealth': 'मिट्टी की सेहत',
      'optimal': 'इष्टतम',
      'nitrogen': 'नाइट्रोजन',
      'high': 'उच्च',
      'phLevel': 'पीएच (pH) स्तर',
      'viewDetailedReport': 'विस्तृत रिपोर्ट देखें',
      'marketPrice': 'बाजार मूल्य',
      'quintal': 'कुंतल',
      'fromLastWeek': 'पिछले सप्ताह से',
      'logHarvest': 'फसल कटाई दर्ज करें',
      'needExpertAdvice': 'विशेषज्ञ की सलाह चाहिए?',
      'helperMic': 'माइक दबाएं और कहें "मेरी टमाटर पत्ती की सेहत जांचें"',
      'quickInsights': 'त्वरित अंतर्दृष्टि',
      'cropGrowthPhase': 'फसल वृद्धि चरण',
      'soybeansStage': 'सोयाबीन: वानस्पतिक चरण (V3)',
      'satelliteView': 'सैटेलाइट फील्ड दृश्य',
      'updatedHoursAgo': '2 घंटे पहले अपडेट किया गया',
      'home': 'होम',
      'advice': 'सलाह',
      'weather': 'मौसम',
      'crops': 'फसलें',
      'expert': 'विशेषज्ञ',
      
      // Advice Tab
      'cropRecommendations': 'फसल अनुशंसाएं',
      'aiDrivenPlanting': 'आपके वर्तमान खेत के डेटा पर आधारित एआई-संचालित रोपण रणनीतियाँ।',
      'soilType': 'मिट्टी का प्रकार',
      'redSoil': 'लाल मिट्टी',
      'richInIron': 'आयरन ऑक्साइड से भरपूर',
      'waterLevel': 'जल स्तर',
      'marketDemand': 'बाजार की मांग',
      'highDemand': 'उच्च मांग',
      'pulseCropsTrend': 'दलहन फसलों का स्थानीय चलन +14%',
      'groundnut': 'मूंगफली',
      'match': 'मैच',
      'potentialYield': 'संभावित उपज',
      'tonsHectare': 'टन/हेक्टेयर',
      'waterReq': 'पानी की आवश्यकता',
      'duration': 'अवधि',
      'days': 'दिन',
      'startPlanting': 'रोपण योजना शुरू करें',
      'pigeonPea': 'अरहर',
      'sorghum': 'ज्वार',
      'viewDetails': 'विवरण देखें',
      'soilNutrientBalance': 'मिट्टी पोषक तत्व संतुलन',
      'nutrientTip': 'सुझाव: लाल मिट्टी में मल्च डालने से अगले चक्र में नमी बनी रहेगी।',
      
      // Weather Tab
      'weatherAdvisory': 'मौसम एवं सलाह',
      'weatherSub': 'आपके खेत के लिए वास्तविक समय की कृषि अंतर्दृष्टि।',
      'drySpellAlert': 'सूखे की चेतावनी',
      'drySpellDesc': 'अगले 10 दिनों में कम बारिश का अनुमान। सेक्टर B-4 में नमी कम हो रही है।',
      'delaySowing': 'बुवाई में देरी करें',
      'increaseWater': 'पानी बढ़ाएं',
      'viewDetailedPlan': 'विस्तृत योजना देखें',
      'currently': 'वर्तमान में',
      'humidity': 'नमी',
      'nextIrrigation': 'अगला सिंचाई समय',
      'recommendedAmt': 'अनुशंसित: 12 लीटर प्रति वर्ग मीटर',
      'outlook': '7-दिवसीय कृषि दृष्टिकोण',
      'mon': 'सोम',
      'tue': 'मंगल',
      'wed': 'बुध',
      'sprayingOk': 'छिड़काव ठीक',
      'fertilize': 'खाद डालें',
      'fertilizerWindow': 'उर्वरक आवेदन समय',
      'optimalTime': 'सर्वोत्तम समय',
      '48hours': '48 घंटों में',
      'soilCondOpt': 'बुधवार की हल्की बारिश के बाद नाइट्रोजन अवशोषण के लिए मिट्टी अनुकूल होगी।',
      'recommended': 'अनुशंसित',
      'ureaApp': 'यूरिया आवेदन (सेक्टर A)',
      'ureaAmount': '50 किग्रा/हेक्टेयर डालें',
      'sensorNetwork': 'मृदा नमी सेंसर नेटवर्क',
      'sensorDesc': '24 IoT ग्राउंड सेंसर से वास्तविक समय का डेटा।',
      'fullscreenMap': 'पूर्ण मानचित्र देखें',
      'thermalView': 'थर्मल दृश्य में बदलें',
      'normalView': 'सामान्य दृश्य में बदलें',

      // Crops Tab
      'myCrops': 'मेरी फसलें',
      'plantedOn': 'रोपण की तारीख',
      'daysRemaining': 'कटाई तक दिन',
      'activeFields': 'सक्रिय खेत क्षेत्र',
      'addNewCrop': 'फसल जोड़ें',
      'logNewHarvest': 'फसल कटाई दर्ज करें',

      // Expert Tab
      'newDiagnosis': 'नया निदान',
      'diagnosisDesc': 'त्वरित एआई-संचालित स्वास्थ्य विश्लेषण के लिए फोटो अपलोड करें या आवाज में समस्या बताएं।',
      'takePhoto': 'फोटो खींचें',
      'processed': 'संसाधित',
      'ongoingDiagnosis': 'चल रहा निदान',
      'analyzingRice': 'धान के ब्लास्ट रोग के लक्षणों का विश्लेषण',
      'crossReference': 'स्थानीय मौसम डेटा और नाइट्रोजन स्तरों के साथ लक्षणों का मिलान...',
      'cancel': 'रद्द करें',
      'rythuExpert': 'रायथू सेवा केंद्र विशेषज्ञ',
      'specialistAvail': 'हमारे स्थानीय विशेषज्ञ आज वीडियो कॉल या क्षेत्र यात्रा के लिए उपलब्ध हैं।',
      'callNow': 'अभी कॉल करें',
      'bookVisit': 'यात्रा बुक करें',
      'historicalLogs': 'ऐतिहासिक लॉग',
      'viewAll': 'सभी देखें',
      'resolved': 'सुलझाया गया',
      'inReview': 'समीक्षा में',
      'tomatoWilt': 'टमाटर का म्लानि (Wilt)',
      'tomatoWiltDesc': 'सफलता: कॉपर कवकनाशी का छिड़काव किया। विकास में 15% सुधार।',
      'maizeChlorosis': 'मक्के का क्लोरोसिस',
      'maizeChlorosisDesc': 'विशेषज्ञ नियुक्त। मिट्टी की नमी विश्लेषण की प्रतीक्षा है।',
      'cottonAphids': 'कपास का एफिड्स',
      'cottonAphidsDesc': 'जैव-कीटनाशक उपचार पूरा हुआ। खेत साफ है।',
    }
  };

  static String text(String key, bool isHindi) {
    String lang = isHindi ? 'hi' : 'en';
    return values[lang]?[key] ?? values['en']?[key] ?? key;
  }
}
